-- ============================================================================
-- SCRIPT COMPLETO DE CONFIGURACIÓN DE ENTORNO SNOWFLAKE PARA WORKSHOP
-- Arquitectura: Medallion + Roles RBAC + Enmascaramiento de datos
-- Autor: Nelson Zepeda
-- ============================================================================

-- ============================================================================
-- 1. CREACIÓN DE WAREHOUSES
-- ============================================================================
CREATE OR REPLACE WAREHOUSE WH_SMALL
  WITH WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Warehouse para usuarios de lectura';

CREATE OR REPLACE WAREHOUSE WH_MID
  WITH WAREHOUSE_SIZE = 'MEDIUM'
  AUTO_SUSPEND = 600
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Warehouse para ETL y procesos medios';

CREATE OR REPLACE WAREHOUSE WH_LARGE
  WITH WAREHOUSE_SIZE = 'LARGE'
  AUTO_SUSPEND = 900
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Warehouse para procesos intensivos';

-- ============================================================================
-- 2. CREACIÓN DE BASE DE DATOS Y ESQUEMAS
-- ============================================================================
CREATE OR REPLACE DATABASE WORKSHOP;

CREATE OR REPLACE SCHEMA WORKSHOP.BRONZE_MERCADEO;
CREATE OR REPLACE SCHEMA WORKSHOP.SILVER_MERCADEO;
CREATE OR REPLACE SCHEMA WORKSHOP.GOLD_MERCADEO;

CREATE OR REPLACE SCHEMA WORKSHOP.BRONZE_VENTAS;
CREATE OR REPLACE SCHEMA WORKSHOP.SILVER_VENTAS;
CREATE OR REPLACE SCHEMA WORKSHOP.GOLD_VENTAS;

CREATE OR REPLACE SCHEMA WORKSHOP.BRONZE_OPERACIONES;
CREATE OR REPLACE SCHEMA WORKSHOP.SILVER_OPERACIONES;
CREATE OR REPLACE SCHEMA WORKSHOP.GOLD_OPERACIONES;

CREATE OR REPLACE SCHEMA WORKSHOP.BRONZE_RECURSOS_HUMANOS;
CREATE OR REPLACE SCHEMA WORKSHOP.SILVER_RECURSOS_HUMANOS;
CREATE OR REPLACE SCHEMA WORKSHOP.GOLD_RECURSOS_HUMANOS;

CREATE OR REPLACE SCHEMA WORKSHOP.SECURITY;