



-- ============================================================================
-- 3. CREACIÓN DE ROLES
-- ============================================================================
CREATE OR REPLACE ROLE ROLE_DEVELOPER;
CREATE OR REPLACE ROLE ROLE_ADMIN_FULL;
CREATE OR REPLACE ROLE ROLE_DEVELOPER;
CREATE OR REPLACE ROLE ROLE_READONLY_MERCADEO;
CREATE OR REPLACE ROLE ROLE_READONLY_VENTAS;
CREATE OR REPLACE ROLE ROLE_READONLY_OPERACIONES;
CREATE OR REPLACE ROLE ROLE_READONLY_RRHH;
CREATE OR REPLACE ROLE ROLE_DATASCIENCE_READONLY;

-- ============================================================================
-- 1. CREACIÓN DE WAREHOUSES
-- ============================================================================
CREATE OR REPLACE WAREHOUSE WH_SMALL
  WITH WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Warehouse para usuarios de lectura';

CREATE OR REPLACE WAREHOUSE WH_MID
  WITH WAREHOUSE_SIZE = 'MEDIUM'
  AUTO_SUSPEND = 600
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Warehouse para ETL y procesos medios';

CREATE OR REPLACE WAREHOUSE WH_LARGE
  WITH WAREHOUSE_SIZE = 'LARGE'
  AUTO_SUSPEND = 900
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Warehouse para procesos intensivos';



-- ============================================================================
-- 4. PERMISOS PARA DEV y ADMIN
-- ============================================================================

-- Acceso a la base de datos
GRANT USAGE ON DATABASE WORKSHOP TO ROLE ROLE_ADMIN_FULL;

-- Acceso a todos los esquemas existentes
GRANT USAGE ON ALL SCHEMAS IN DATABASE WORKSHOP TO ROLE ROLE_ADMIN_FULL;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE WORKSHOP TO ROLE ROLE_ADMIN_FULL;

-- Permisos sobre esquemas futuros
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE WORKSHOP TO ROLE ROLE_ADMIN_FULL;

-- Acceso a objetos EXISTENTES dentro del esquema BRONZE_MERCADEO 
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA WORKSHOP.BRONZE_MERCADEO TO ROLE ROLE_ADMIN_FULL;
GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA WORKSHOP.BRONZE_MERCADEO TO ROLE ROLE_ADMIN_FULL;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA WORKSHOP.BRONZE_MERCADEO TO ROLE ROLE_ADMIN_FULL;
GRANT ALL PRIVILEGES ON ALL PROCEDURES IN SCHEMA WORKSHOP.BRONZE_MERCADEO TO ROLE ROLE_ADMIN_FULL;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA WORKSHOP.BRONZE_MERCADEO TO ROLE ROLE_ADMIN_FULL;

-- Acceso a objetos FUTUROS dentro del esquema PUBLIC
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA WORKSHOP.BRONZE_MERCADEO TO ROLE ROLE_ADMIN_FULL;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA WORKSHOP.BRONZE_MERCADEO TO ROLE ROLE_ADMIN_FULL;
GRANT ALL PRIVILEGES ON FUTURE FUNCTIONS IN SCHEMA WORKSHOP.BRONZE_MERCADEO TO ROLE ROLE_ADMIN_FULL;
GRANT ALL PRIVILEGES ON FUTURE PROCEDURES IN SCHEMA WORKSHOP.BRONZE_MERCADEO TO ROLE ROLE_ADMIN_FULL;
GRANT ALL PRIVILEGES ON FUTURE SEQUENCES IN SCHEMA WORKSHOP.BRONZE_MERCADEO TO ROLE ROLE_ADMIN_FULL;

-- Acceso completo a los warehouses
GRANT ALL PRIVILEGES ON WAREHOUSE WH_SMALL TO ROLE ROLE_ADMIN_FULL;
GRANT ALL PRIVILEGES ON WAREHOUSE WH_MID TO ROLE ROLE_ADMIN_FULL;
GRANT ALL PRIVILEGES ON WAREHOUSE WH_LARGE TO ROLE ROLE_ADMIN_FULL;

-- Permisos sobre futuros stages
GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA WORKSHOP.BRONZE_MERCADEO TO ROLE ROLE_ADMIN_FULL;


-- (Opcional) Permitir que este rol otorgue los mismos privilegios a otros roles
-- GRANT ALL PRIVILEGES ON DATABASE WORKSHOP TO ROLE ROLE_ADMIN_FULL WITH GRANT OPTION;
-- GRANT ALL PRIVILEGES ON WAREHOUSE WH_SMALL TO ROLE ROLE_ADMIN_FULL WITH GRANT OPTION;

-- (Opcional) Asignar el rol a tu usuario
-- GRANT ROLE ROLE_ADMIN_FULL TO USER TU_USUARIO;



-- Dar acceso a la base de datos y todos los esquemas existentes
GRANT USAGE ON DATABASE WORKSHOP TO ROLE ROLE_DEVELOPER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE WORKSHOP TO ROLE ROLE_DEVELOPER;
-- Permisos de creación sobre todos los esquemas existentes
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, 
      CREATE FUNCTION, CREATE PROCEDURE, CREATE TASK, CREATE SEQUENCE 
ON ALL SCHEMAS IN DATABASE WORKSHOP TO ROLE ROLE_DEVELOPER;
-- Permisos sobre tablas existentes en cada esquema (esto deberías hacerlo por cada schema si no usas wildcard scripting)
GRANT SELECT, INSERT, UPDATE, DELETE 
ON ALL TABLES IN SCHEMA WORKSHOP.BRONZE_MERCADEO TO ROLE ROLE_DEVELOPER;
-- Permisos sobre objetos futuros en todos los esquemas
GRANT SELECT, INSERT, UPDATE, DELETE 
ON FUTURE TABLES IN SCHEMA WORKSHOP.BRONZE_MERCADEO TO ROLE ROLE_DEVELOPER;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA WORKSHOP.BRONZE_MERCADEO TO ROLE ROLE_DEVELOPER;
--GRANT EXECUTE ON FUTURE PROCEDURES IN SCHEMA WORKSHOP.BRONZE_MERCADEO TO ROLE ROLE_DEVELOPER; versiones enterprise
-- Acceso a los warehouses
GRANT USAGE ON WAREHOUSE WH_SMALL TO ROLE ROLE_DEVELOPER;
GRANT USAGE ON WAREHOUSE WH_MID TO ROLE ROLE_DEVELOPER;
GRANT USAGE ON WAREHOUSE WH_LARGE TO ROLE ROLE_DEVELOPER;




-- ============================================================================
-- 5. PERMISOS DE LECTURA PARA ROLES FUNCIONALES
-- ============================================================================
-- MERCADEO
GRANT USAGE ON DATABASE WORKSHOP TO ROLE ROLE_READONLY_MERCADEO;
GRANT USAGE ON SCHEMA WORKSHOP.GOLD_MERCADEO TO ROLE ROLE_READONLY_MERCADEO;
GRANT SELECT ON ALL TABLES IN SCHEMA WORKSHOP.GOLD_MERCADEO TO ROLE ROLE_READONLY_MERCADEO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA WORKSHOP.GOLD_MERCADEO TO ROLE ROLE_READONLY_MERCADEO;
GRANT USAGE ON WAREHOUSE WH_SMALL TO ROLE ROLE_READONLY_MERCADEO;


-- Agregar los otros roles cambiando el esquema si aplica
-- Ventas, Operaciones, RRHH...

-- DataScience
GRANT USAGE ON DATABASE WORKSHOP TO ROLE ROLE_DATASCIENCE_READONLY;
GRANT USAGE ON ALL SCHEMAS IN DATABASE WORKSHOP TO ROLE ROLE_DATASCIENCE_READONLY;
GRANT SELECT ON ALL TABLES IN DATABASE WORKSHOP TO ROLE ROLE_DATASCIENCE_READONLY;
GRANT SELECT ON FUTURE TABLES IN DATABASE WORKSHOP TO ROLE ROLE_DATASCIENCE_READONLY;
GRANT USAGE ON WAREHOUSE WH_SMALL TO ROLE ROLE_DATASCIENCE_READONLY;

-- ============================================================================
-- 6. CREACIÓN DE USUARIOS Y ASIGNACIÓN DE ROLES
-- ============================================================================
CREATE OR REPLACE USER usuario_admin PASSWORD='Admin#2025' DEFAULT_ROLE=ROLE_ADMIN_FULL DEFAULT_WAREHOUSE=WH_SMALL;
CREATE OR REPLACE USER usuario_mercadeo PASSWORD='Mercadeo#2025' DEFAULT_ROLE=ROLE_READONLY_MERCADEO DEFAULT_WAREHOUSE=WH_SMALL;
CREATE OR REPLACE USER usuario_datascience PASSWORD='DataScience#2025' DEFAULT_ROLE=ROLE_DATASCIENCE_READONLY DEFAULT_WAREHOUSE=WH_SMALL;
CREATE OR REPLACE USER usuario_developer PASSWORD='Dev#2025' DEFAULT_ROLE=ROLE_DEVELOPER DEFAULT_WAREHOUSE=WH_SMALL;

-- Agrega más usuarios si deseas

GRANT ROLE ROLE_ADMIN_FULL TO USER usuario_admin;
GRANT ROLE ROLE_READONLY_MERCADEO TO USER usuario_mercadeo;
GRANT ROLE ROLE_DATASCIENCE_READONLY TO USER usuario_datascience;
GRANT ROLE ROLE_DEVELOPER TO USER usuario_developer;

-- Asignar roles al usuario ADMIN nativo
GRANT ROLE ROLE_ADMIN_FULL TO USER ADMIN;
GRANT ROLE ROLE_READONLY_MERCADEO TO USER ADMIN;
GRANT ROLE ROLE_DATASCIENCE_READONLY TO USER ADMIN;
GRANT ROLE ROLE_DEVELOPER TO USER ADMIN;

-- Hacer que ROLE_ADMIN_FULL herede todos los permisos de ROLE_DEVELOPER
GRANT ROLE ROLE_DEVELOPER TO ROLE ROLE_ADMIN_FULL;
